disabled_rules:
  - identifier_name
  - todo
  - file_length
  - type_body_length
  - function_body_length
  - cyclomatic_complexity
  - large_tuple
  - closure_parameter_position
  - force_try
included:
  - Sources
  - Tests
