matrix:
  include:
  - os: linux
    language: generic
    sudo: required
    dist: trusty
    if: NOT tag IS present OR tag =~ ^*-linux$
    before_install:
    - sudo add-apt-repository -y ppa:ethereum/ethereum
    - sudo apt-get update
    - sudo apt-get -y install solc
    - npm install -g truffle
    install:
    - eval "$(curl -sL https://swiftenv.fuller.li/install.sh)"
    script:
    - make test
  - os: osx
    language: objective-c
    osx_image: xcode9
    if: tag =~ ^*-macos$
before_deploy:
- make release
deploy:
  provider: releases
  api_key:
    secure: y5tGPDW15dRTrrtzQOKmRGIHYQ9aIq5EHUDzsgEGTE3MzJ0xt3WfhTSDH5aR9MDOtj8tS8Pdj8ZAhXNidIMIsbY0oy4okvHqRxMgcdOEdD/9u240la1zzVA4LBWujmwsRMe1BAoqtIyO71XTsTBBqd+6T/upmgDLb+CXuCHTKMNBdBp+Nke4jaM1zVrIJLpHQh7NGh/wbaUo07uPudGR9jz9DhVO9tY3sd2YiXcWGEo3x11PTXRYrkSICkShWJcpuFZpDJL85fCeUqPY+gj1SObWtuFvRfsJnBF/6rhiGVNdBvHV/hZwp9Jg603WsHQuTcYhQkp3wZx66mHqUjtdZ6eIeCVenG8gmpndQIzeLbs9DKF/9/zpk5G4vrGIC4mPyKA4JrNHg+vgxCi0EryPwqMBz9CT1IWwZSl6lFmKLiFmbXEyEOM2jwUKn3yguqW0ExDj4/vdB21BziyNVIBg5Su6GrMyEVCDyQo09a7qWHCF/R66GgVVqGuvlok8gruEDjl2YQW9pOHcFNt8I18xcIK+ZjgNZ+iRB2csGNPuA6Io8a5CN2Xlp1AzhgQPOrkdrej1T3bjCbxfUqDUus6go8ywX2e9jQZv8kaYjQi2hnqxw3mmZF3n5sstoMo4vcI66qipJFtlcPjF7Ct4EHBWA0213+Z3FEA1L7n8cuS2N+8=
  file: flintc.zip
  on:
    repo: franklinsch/flint
