matrix:
  include:
  - os: linux
    language: generic
    sudo: required
    dist: bionic
    if: NOT tag IS present OR tag =~ ^*-linux$
    before_install:
    - sudo apt-get update
    - sudo apt-get install -y software-properties-common curl git zip sudo wget gnupg ca-certificates apt-transport-https sed python python3
    - sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 3FA7E0328081BFF6A14DA29AA6A19B38D3D831EF
    - echo "deb https://download.mono-project.com/repo/ubuntu stable-bionic main" | sudo tee /etc/apt/sources.list.d/mono-official-stable.list
    - sudo add-apt-repository -y ppa:ethereum/ethereum
    - curl -sL https://deb.nodesource.com/setup_11.x | sudo -E bash -
    - sudo apt-get update
    - sudo apt-get install -y solc nodejs mono-complete
    - test -f /usr/bin/msbuild && echo "msbuild exists"
    - npm install
    - npm install -g truffle@4
    - eval "$(curl -sL https://swiftenv.fuller.li/install.sh)"
    - git clone https://github.com/realm/SwiftLint.git /tmp/swiftlint
    - (cd /tmp/swiftlint; swiftenv install; swift build -c release --static-swift-stdlib)
    - export PATH="/tmp/swiftlint/.build/x86_64-unknown-linux/release:$PATH"
    install:
    - "swiftenv install 5.0.2 || true"
    - "swiftenv install 4.2 || true"
    script:
    - wget 
    - export FLINTPATH=$(pwd)
    - make
    - sed -i -e "s/ as / as! /g" ".build/checkouts/Cuckoo/Source/Initialization/ThreadLocal.swift" 
    - make test
before_deploy:
- swift package update
- make release
- make zip
deploy:
  provider: releases
  skip_cleanup: true
  file: flintc.zip
  on:
    repo: matteobilardi/flint
    tags: true
