matrix:
  include:
  - os: linux
    language: generic
    sudo: required
    dist: trusty
    if: NOT tag IS present OR tag =~ ^*-linux$
    before_install:
      - sudo add-apt-repository -y ppa:ethereum/ethereum
      - sudo apt-get update
      - sudo apt-get -y install solc
      - npm install -g truffle
    install:
      - eval "$(curl -sL https://swiftenv.fuller.li/install.sh)"
    script:
      - make test
  - os: osx
    language: objective-c
    osx_image: xcode9
    if: tag =~ ^*-macos$
    before_install:
      - brew update
      - brew upgrade
      - brew tap ethereum/ethereum
      - brew install solidity
      - brew linkapps solidity
      - npm install -g truffle
    install:
      - eval "$(curl -sL https://swiftenv.fuller.li/install.sh)"
    script:
      - make test

before_deploy:
- make release
deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: f1Dt+H2g5LUuYmuEqF/c4F4C03eVzsBnVyOZLBHwmytuU3b8oCGUAJz+I2kywrUjxJxFpkwPsMwiUNjqn5qsDgxpmjOOVuFrignrx7Wbxe3tfzZp2wmhSt74DE+DDs8GPge6Cf2V05Vjpgzluc8DfEEpCTzOTFiqXWwExemSUXMo6Wt/kDt9NTSS5DJDx0Do8OIvnWcgina0dYxGWhiOdE5qN7uwh+iEU1lAY5dX/SFcX9ZcXtle5J3Nhm6C/hZuVGTSkzrjG8Gxc30y/6nEpZ2sjZ0b/Y6HY3/dwmiERJIgqAEnZx/CBL3RvCDcDG3oCAvfLNcxx3zzToPo6dnAlb/FnTLLD1sShIPyVPZtCNSBlQsalRoz2vASvPv4qLfcMEYy1F7sNYM8NYEkrQERDvqJe5kr8vzULN7iyAe7v4/GjgOD3FYVPasqtGAQDNlA6yvqabKdngxJ9gBjpBGgL44bN8WjYI08PAfAqjPchF41ggUWXKRrszMMsFn/3YtuNgW4rICYzKi+CEHLLge0AR0GP5pgYjscWO/9PfrrkGOK3Xpi2qmnDVBAEtEBBB+YUvX+AFZmYjLr4IG44OARvXFeKFbiiuybWOPOmJ3vlzBlkZRMvx3Gbog15tte/NlmjA4NADKWUcvQDKnQY2Y7JzBbAZyG0sXWec7VRgY+Las=
  file: ".build/release/flintc"
  on:
    repo: franklinsch/flint
    tags: true
